#! /bin/sh

# If you don't use rpm, you can use this file to apply additional Linux
# patches. At the top level of the binutils source tree, do
#
# /bin/sh patches/README
#
# You may have to do
#
# cd bfd
# make headers
#
# if the build fails.

dir=`dirname $0`
clean=$1

patches="
0001-Linux-x86-Configure-gas-with-enable-x86-used-note-by.patch
0001-gold-Discard-.note.gnu.property-section.patch
0002-gold-Support-GNU_PROPERTY_X86_FEATURE_2_-USED-NEEDED.patch
0003-gold-Discard-.note.gnu.property-for-PR-gold-23503.patch
0004-gold-Skip-some-incremental-tests.patch
0005-gold-Properly-align-the-NT_GNU_PROPERTY_TYPE_0-note.patch
0001-gold-Ignore-gnu.build.attributes-section.patch
0001-gold-Update-ver_test_pr16504.sh.patch
0001-gold-Fix-script_test_7.sh-script_test_9.sh.patch
0001-gold-x86-64-Fix-TLSDESC-LE-relaxation.patch
0002-gold-x86-64-Fix-TLSDESC-relaxation-for-x32.patch
0001-gold-Make-Ordering-operator-even-more-complex.patch
0001-Don-t-claim-a-fat-IR-object-if-no-IR-object-should-b.patch
0001-Add-lto-and-none-lto-input-support-for-ld-r.patch
0002-Add-test-for-nm-on-mixed-LTO-non-LTO-object.patch
0003-Don-t-check-the-plugin-target-twice.patch
0001-ELF-Strip-section-header-in-ELF-objects.patch
0002-bfd-Improve-nm-and-objdump-without-section-header.patch
0003-ld-Add-a-simple-test-for-z-nosectionheader.patch
0004-binutils-Add-a-strip-sections-test.patch
0005-ld-Add-tests-for-z-nosectionheader-and-strip-section.patch
0006-ld-Add-z-nosectionheader-test-to-bootstrap.exp.patch
0001-gas-Extend-.symver-directive.patch
0001-Add-STB_SECONDARY-support.patch
	binutils-x86-optimize-option.patch
	binutils-attach-to-group.patch
"

for p in $patches
do
  if [ ! -n "$clean" ]
  then
    suffix=$(echo $p | sed -e "s/.*-\([^-]\+\).patch/\1/")
    backup="-b --suffix .$suffix"
  fi
  patch --follow-symlinks -E -p1 $backup < $dir/$p || exit 1
done
find -name "*.orig" | xargs rm -fv
find -name "*.gmo" | xargs rm -fv
