#! /bin/sh

# If you don't use rpm, you can use this file to apply additional Linux
# patches. At the top level of the binutils source tree, do
#
# /bin/sh patches/README
#
# You may have to do
#
# cd bfd
# make headers
#
# if the build fails.

dir=`dirname $0`
clean=$1

patches="
0001-Linux-x86-Configure-gas-with-enable-x86-used-note-by.patch
0001-Set-DEMANGLE_RECURSION_LIMIT-to-1536.patch
0001-gold-Discard-.note.gnu.property-section.patch
0002-gold-Support-GNU_PROPERTY_X86_FEATURE_2_-USED-NEEDED.patch
0003-gold-Discard-.note.gnu.property-for-PR-gold-23503.patch
0004-gold-Pass-Wa-mx86-used-note-no-to-COMPILE-CXXCOMPILE.patch
0005-gold-Properly-align-the-NT_GNU_PROPERTY_TYPE_0-note.patch
0001-gold-Ignore-gnu.build.attributes-section.patch
0001-Override-the-previous-definition-from-IR-object.patch
0001-Don-t-claim-a-fat-IR-object-if-no-IR-object-should-b.patch
	binutils-lto-mixed.patch
	binutils-lto-mixed-test.patch
	binutils-lto-mixed-plugin.patch
	binutils-pr12639.patch
	binutils-secondary.patch
	binutils-pr21128.patch
	binutils-pr21129.patch
	binutils-x86-64-thunk.patch
	binutils-x86-64-gold-thunk.patch
	binutils-x86-gpoff.patch
	binutils-x86-optimize-option.patch
"

for p in $patches
do
  if [ ! -n "$clean" ]
  then
    suffix=$(echo $p | sed -e "s/.*-\([^-]\+\).patch/\1/")
    backup="-b --suffix .$suffix"
  fi
  patch --follow-symlinks -E -p1 $backup < $dir/$p || exit 1
done
find -name "*.orig" | xargs rm -fv
find -name "*.gmo" | xargs rm -fv
